### ISSUE TITLE
Signal-Receiver won't work sporadically

### ISSUE THREAD

**Issue by andscor** [useblocks/groundwork#14]
> Status:

During the execution of the application seems like that some signals don't communicate with their corresponding receivers.

> Example:

The function get_project_data() is implemented inside the plugin "exporter_plugin". Inside the plugin is also declared the corresponding receiver:

`class ExporterPlugin(DatabasePattern):`
`def activate(self):`
`self.signals.connect(receiver="project data receiver", signal="project data", function=self.get_project_data,  description="Download data")`
...
`    def get_project_data(self, plugin, project, milestone):`
`# function does something`
`print("project_data_dict", project_data_dict)`
`return project_data_dict`

The plugin "excel_plugin" registers the signal "project data" and calls it inside a function:

`class ExcelPlugin(RmExcelPattern):`
`def activate(self):`
`self.signals.register(signal="project data", description="Request data")`
...
`def foo(self, project, milestone):`
`result_data = self.signals.send("project data", project=project, milestone=milestone)`
`print("result_data", result_data)`

> Result

The variable project_data is a void array:
`>> result_data []`
The function get_project_data is not executed (no "project_data_dict" is displayed before "result_data")
All plugins are loaded correctly.

**Comment by danwos** [comment]
Hi Andscor,
thanks for the bug report and welcome on github!

We had some similar reports in the past and I will try to write a test case to reproduce this error.
So your example code is highly welcome.

**Comment by danwos** [comment]
Finally a solution. Sorry for taking soo long...

However, I wasn't so easy to find a reproducible test setup.
But it's done now and the fix was quite easy.
We stopped using `WeakNamespace` from the underlying library blinker. Instead we are using the "normal `Namespace` class.
This may lead us to some extra work in groundwork itself, if automatic clean ups of receivers/sender may become an issue. But currently all test passed.

I haven't release a version yet. But the fix is already part of the latest master.
